"""Contracts for deterministic cleaning and normalization."""

from __future__ import annotations

from enum import StrEnum

from pydantic import Field, model_validator

from rageval.models.contracts import ContractModel, DocumentElement, DocumentRecord


class UnicodeForm(StrEnum):
    """Supported deterministic Unicode normalization forms."""

    NFC = "NFC"
    NFKC = "NFKC"


class RemovalReason(StrEnum):
    """Auditable reasons why a parsed element did not survive cleaning."""

    REPEATED_HEADER = "repeated_header"
    REPEATED_FOOTER = "repeated_footer"
    PAGE_NUMBER = "page_number"
    DUPLICATE_BOILERPLATE = "duplicate_boilerplate"
    NEAR_DUPLICATE_BOILERPLATE = "near_duplicate_boilerplate"
    EMPTY_AFTER_NORMALIZATION = "empty_after_normalization"


class CleaningConfig(ContractModel):
    """Versioned configuration that fully determines cleaning behavior."""

    schema_version: str = "1.0"
    cleaner_version: str = "phase4-1.0"
    unicode_form: UnicodeForm = UnicodeForm.NFKC
    remove_control_characters: bool = True
    collapse_whitespace: bool = True
    join_hyphenated_linebreaks: bool = True
    suppress_repeated_headers_footers: bool = True
    repeated_pattern_min_pages: int = Field(default=2, ge=2)
    canonicalize_page_numbers: bool = True
    deduplicate_boilerplate: bool = True
    dedup_similarity_threshold: float = Field(default=0.92, ge=0.0, le=1.0)
    dedup_min_pages: int = Field(default=3, ge=2)
    dedup_min_chars: int = Field(default=24, ge=1)
    dedup_max_chars: int = Field(default=320, ge=1)
    boilerplate_markers: tuple[str, ...] = (
        "confidential",
        "all rights reserved",
        "forward-looking",
        "not for distribution",
        "proprietary",
        "disclaimer",
        "generated by",
    )

    @model_validator(mode="after")
    def validate_dedup_bounds(self) -> CleaningConfig:
        """Keep duplicate-candidate length bounds coherent."""
        if self.dedup_max_chars < self.dedup_min_chars:
            raise ValueError("dedup_max_chars must be >= dedup_min_chars")
        return self


class RemovalEvidence(ContractModel):
    """Evidence explaining an element removal without losing source traceability."""

    source_element_id: str = Field(min_length=8)
    reason: RemovalReason
    page_number: int | None = Field(default=None, ge=1)
    matched_source_element_id: str | None = None
    similarity: float | None = Field(default=None, ge=0.0, le=1.0)
    pattern_signature: str | None = None
    original_text: str = ""


class CleaningStats(ContractModel):
    """Per-document cleaning statistics produced by an actual cleaning run."""

    elements_in: int = Field(ge=0)
    elements_out: int = Field(ge=0)
    duplicates_removed: int = Field(ge=0)
    boilerplate_removed: int = Field(ge=0)
    header_footer_removed: int = Field(ge=0)
    page_numbers_removed: int = Field(ge=0)
    ocr_elements: int = Field(ge=0)
    tables_preserved: int = Field(ge=0)
    characters_in: int = Field(ge=0)
    characters_out: int = Field(ge=0)
    characters_removed: int = Field(ge=0)


class CleanedDocument(ContractModel):
    """Retrieval-ready normalized elements plus cleaning evidence and provenance."""

    document: DocumentRecord
    source_parser_name: str = Field(min_length=1)
    source_parser_version: str = Field(min_length=1)
    source_parser_config_fingerprint: str = Field(pattern=r"^[0-9a-f]{64}$")
    cleaning_config_fingerprint: str = Field(pattern=r"^[0-9a-f]{64}$")
    elements: tuple[DocumentElement, ...]
    removals: tuple[RemovalEvidence, ...] = ()
    stats: CleaningStats
    metadata: dict[str, object] = Field(default_factory=dict)
